package fe.db;
// Generated 6/04/2018 03:52:38 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CServiciosFacturacion generated by hbm2java
 */
@Entity
@Table(name="C_SERVICIOS_FACTURACION"
    ,catalog="FACCORP_APL"
)
public class CServiciosFacturacion  implements java.io.Serializable {


     private Integer id;
     private String servicio;
     private Set<MServiciosFacturacion> MServiciosFacturacions = new HashSet<MServiciosFacturacion>(0);

    public CServiciosFacturacion() {
    }

	
    public CServiciosFacturacion(String servicio) {
        this.servicio = servicio;
    }
    public CServiciosFacturacion(String servicio, Set<MServiciosFacturacion> MServiciosFacturacions) {
       this.servicio = servicio;
       this.MServiciosFacturacions = MServiciosFacturacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="servicio", nullable=false)
    public String getServicio() {
        return this.servicio;
    }
    
    public void setServicio(String servicio) {
        this.servicio = servicio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="CServiciosFacturacion")
    public Set<MServiciosFacturacion> getMServiciosFacturacions() {
        return this.MServiciosFacturacions;
    }
    
    public void setMServiciosFacturacions(Set<MServiciosFacturacion> MServiciosFacturacions) {
        this.MServiciosFacturacions = MServiciosFacturacions;
    }




}


